"""Add sharing columns to Entity model

Revision ID: 18a0ba02b776
Revises: 9433e26c4ce2
Create Date: 2025-03-20 15:08:01.761689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a0ba02b776'
down_revision = '9433e26c4ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shared_with', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_column('shared_with')
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
