"""Add visited and properties columns to Entity

Revision ID: 516a29700c27
Revises: 19c78ed7657a
Create Date: 2025-03-01 17:22:00.595265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516a29700c27'
down_revision = '19c78ed7657a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('properties', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_column('properties')
        batch_op.drop_column('visited')

    # ### end Alembic commands ###
