"""Add weekday_options field to schedule table

Revision ID: 6d2f7b8dce27
Revises: ce540affeb30
Create Date: 2025-05-03 17:37:27.050470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2f7b8dce27'
down_revision = 'ce540affeb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekday_options', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('enabled')
        batch_op.drop_column('weekday_options')

    # ### end Alembic commands ###
