"""Add calendar_dates column to Schedule model

Revision ID: 7d02d3be3adc
Revises: 18a0ba02b776
Create Date: 2025-05-03 16:07:00.314595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d02d3be3adc'
down_revision = '18a0ba02b776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_dates', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('calendar_dates')

    # ### end Alembic commands ###
