"""change_schedule_time_columns_to_integer

Revision ID: 9433e26c4ce2
Revises: 007d5fef969b
Create Date: 2025-03-14 18:06:34.267180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9433e26c4ce2'
down_revision = '007d5fef969b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
