"""Change calendar_dates to annual_dates in Schedule model

Revision ID: ce540affeb30
Revises: 7d02d3be3adc
Create Date: 2025-05-03 16:13:31.192219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ce540affeb30'
down_revision = '7d02d3be3adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annual_dates', sa.JSON(), nullable=True))
        batch_op.drop_column('calendar_dates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_dates', sqlite.JSON(), nullable=True))
        batch_op.drop_column('annual_dates')

    # ### end Alembic commands ###
