"""Add user_id to Entity model with named constraint

Revision ID: e7302255774f
Revises: 516a29700c27
Create Date: 2025-03-02 12:36:52.272792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7302255774f'
down_revision = '516a29700c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_entity_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_constraint('fk_entity_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
